// apps/react-todo-apps/src/components/Filters.jsx
import React from 'react';
import styles from './Filters.module.css';

const Filters = ({onFilterChange, filter}) => {
    return (
        <div className={styles.filters}>
            <button
                onClick={() => onFilterChange('all')}
                className={filter === 'all' ? styles.active : ''}
            >
                All
            </button>
            <button
                onClick={() => onFilterChange('active')}
                className={filter === 'active' ? styles.active : ''}
            >
                Active
            </button>
            <button
                onClick={() => onFilterChange('completed')}
                className={filter === 'completed' ? styles.active : ''}
            >
                Completed
            </button>
            <button
                onClick={() => onFilterChange('highPriority')}
                className={filter === 'highPriority' ? styles.active : ''}
            >
                High Priority
            </button>
            <button
                onClick={() => onFilterChange('mediumPriority')}
                className={filter === 'mediumPriority' ? styles.active : ''}
            >
                Medium Priority
            </button>
            <button
                onClick={() => onFilterChange('lowPriority')}
                className={filter === 'lowPriority' ? styles.active : ''}
            >
                Low Priority
            </button>
            <button
                onClick={() => onFilterChange('overdue')}
                className={filter === 'overdue' ? styles.active : ''}
            >
                Overdue
            </button>
        </div>
    );
};

export default Filters;

// apps/vue-todo-apps/src/components/Filters.vue
<script setup lang="ts">
import { useTaskStore } from '../stores/taskStore';
import styles from '../styles/Filters.module.css';

// Get the task store
const taskStore = useTaskStore();

// Handles the clicks on the filter buttons
const onFilterClick = (filterValue: string) => {
  taskStore.setFilter(filterValue);
};

// Checks if the filter is active
const isActive = (filterValue: string) => {
  return taskStore.filter === filterValue;
};
</script>

<template>
  <div :class="styles.filters">
    <button
      @click="onFilterClick('all')"
      :class="{ [styles.active]: isActive('all') }"
    >
      All
    </button>
    <button
      @click="onFilterClick('active')"
      :class="{ [styles.active]: isActive('active') }"
    >
      Active
    </button>
    <button
      @click="onFilterClick('completed')"
      :class="{ [styles.active]: isActive('completed') }"
    >
      Completed
    </button>
    <button
      @click="onFilterClick('highPriority')"
      :class="{ [styles.active]: isActive('highPriority') }"
    >
      High Priority
    </button>
    <button
      @click="onFilterClick('mediumPriority')"
      :class="{ [styles.active]: isActive('mediumPriority') }"
    >
      Medium Priority
    </button>
    <button
      @click="onFilterClick('lowPriority')"
      :class="{ [styles.active]: isActive('lowPriority') }"
    >
      Low Priority
    </button>
    <button
      @click="onFilterClick('overdue')"
      :class="{ [styles.active]: isActive('overdue') }"
    >
      Overdue
    </button>
  </div>
</template>
