// apps/angular-todo-apps/src/app/components/filters/filters.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
// Filters component
@Component({
  selector: 'app-filters',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './filters.component.html',
  styleUrl: './filters.component.css'
})
// Filters component class
export class FiltersComponent {
  @Input() filter: string = 'all';
  @Output() filterChange = new EventEmitter<string>();
// Handles the clicks on the filter buttons
  onFilterClick(filterValue: string): void {
    this.filterChange.emit(filterValue);
  }
// Checks if the filter is active
  isActive(filterValue: string): boolean {
    return this.filter === filterValue;
  }
}

<div class="filters">
  <button
    (click)="onFilterClick('all')"
    [class.active]="isActive('all')"
  >
    All
  </button>
  <button
    (click)="onFilterClick('active')"
    [class.active]="isActive('active')"
  >
    Active
  </button>
  <button
    (click)="onFilterClick('completed')"
    [class.active]="isActive('completed')"
  >
    Completed
  </button>
  <button
    (click)="onFilterClick('highPriority')"
    [class.active]="isActive('highPriority')"
  >
    High Priority
  </button>
  <button
    (click)="onFilterClick('mediumPriority')"
    [class.active]="isActive('mediumPriority')"
  >
    Medium Priority
  </button>
  <button
    (click)="onFilterClick('lowPriority')"
    [class.active]="isActive('lowPriority')"
  >
    Low Priority
  </button>
  <button
    (click)="onFilterClick('overdue')"
    [class.active]="isActive('overdue')"
  >
    Overdue
  </button>
</div>

// apps/vue-todo-apps/src/components/Filters.vue
<script setup lang="ts">
import { useTaskStore } from '../stores/taskStore';
import styles from '../styles/Filters.module.css';

// Get the task store
const taskStore = useTaskStore();

// Handles the clicks on the filter buttons
const onFilterClick = (filterValue: string) => {
  taskStore.setFilter(filterValue);
};

// Checks if the filter is active
const isActive = (filterValue: string) => {
  return taskStore.filter === filterValue;
};
</script>

<template>
  <div :class="styles.filters">
    <button
      @click="onFilterClick('all')"
      :class="{ [styles.active]: isActive('all') }"
    >
      All
    </button>
    <button
      @click="onFilterClick('active')"
      :class="{ [styles.active]: isActive('active') }"
    >
      Active
    </button>
    <button
      @click="onFilterClick('completed')"
      :class="{ [styles.active]: isActive('completed') }"
    >
      Completed
    </button>
    <button
      @click="onFilterClick('highPriority')"
      :class="{ [styles.active]: isActive('highPriority') }"
    >
      High Priority
    </button>
    <button
      @click="onFilterClick('mediumPriority')"
      :class="{ [styles.active]: isActive('mediumPriority') }"
    >
      Medium Priority
    </button>
    <button
      @click="onFilterClick('lowPriority')"
      :class="{ [styles.active]: isActive('lowPriority') }"
    >
      Low Priority
    </button>
    <button
      @click="onFilterClick('overdue')"
      :class="{ [styles.active]: isActive('overdue') }"
    >
      Overdue
    </button>
  </div>
</template>
