// apps/angular-todo-apps/src/app/components/task-form/task-form.component.ts
import {Component, EventEmitter, Output} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {Task} from '../../models/task';

// Task form component to add new tasks
@Component({
  selector: 'app-task-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './task-form.component.html',
  styleUrl: './task-form.component.css'
})
export class TaskFormComponent {
  // Event emitter to send new task to parent
  @Output() addTask = new EventEmitter<Omit<Task, 'id'>>();

  // Form fields
  text: string = '';
  priority: 'High' | 'Medium' | 'Low' = 'Medium';
  dueDate: string = '';
  error: string = '';

  // Handles form submission
  handleSubmit(): void {
    // Validate task description
    if (this.text.trim() === '') {
      this.error = 'Task description is required.';
      return;
    }

    this.error = '';

    // Create new task object
    const newTask: Omit<Task, 'id'> = {
      text: this.text.trim(),
      priority: this.priority,
      dueDate: this.dueDate,
      completed: false
    };

    // Emit new task and reset form
    this.addTask.emit(newTask);
    this.resetForm();
  }

  // Reset form to initial state
  resetForm(): void {
    this.text = '';
    this.priority = 'Medium';
    this.dueDate = '';
  }
}

<!-- Task form with submission handler -->
<form (ngSubmit)="handleSubmit()" class="taskForm">
  <!-- Error message displayed when validation fails -->
  <div *ngIf="error" class="errorMessage">{{ error }}</div>

  <!-- Task description input field -->
  <div class="formGroup">
    <label for="taskText" class="label">Task Description:</label>
    <input
      type="text"
      id="taskText"
      [(ngModel)]="text"
      name="text"
      placeholder="Enter task description"
      class="inputField"
      required
    />
  </div>

  <!-- Priority selection dropdown -->
  <div class="formGroup">
    <label for="taskPriority" class="label">Priority:</label>
    <select
      id="taskPriority"
      [(ngModel)]="priority"
      name="priority"
      class="selectField"
    >
      <option value="High">High</option>
      <option value="Medium">Medium</option>
      <option value="Low">Low</option>
    </select>
  </div>

  <!-- Due date input field -->
  <div class="formGroup">
    <label for="taskDueDate" class="label">Due Date:</label>
    <input
      type="date"
      id="taskDueDate"
      [(ngModel)]="dueDate"
      name="dueDate"
      class="dateField"
    />
  </div>

  <!-- Submit button to add the task -->
  <button type="submit" class="submitButton">
    Add Task
  </button>
</form>

// apps/vue-todo-apps/src/components/TaskForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useTaskStore } from '../stores/taskStore';
import styles from '../styles/TaskForm.module.css';

// Get the task store
const taskStore = useTaskStore();

// Form fields
const text = ref('');
const priority = ref<'High' | 'Medium' | 'Low'>('Medium');
const dueDate = ref('');
const error = ref('');

// Handles form submission
const handleSubmit = () => {
  // Validate task description
  if (text.value.trim() === '') {
    error.value = 'Task description is required.';
    return;
  }

  error.value = '';

  // Create new task object and add it to the store
  taskStore.addTask({
    text: text.value.trim(),
    priority: priority.value,
    dueDate: dueDate.value,
    completed: false
  });

  // Reset form
  resetForm();
};

// Reset form to initial state
const resetForm = () => {
  text.value = '';
  priority.value = 'Medium';
  dueDate.value = '';
};
</script>

<template>
  <!-- Task form with submission handler -->
  <form @submit.prevent="handleSubmit" :class="styles.taskForm">
    <!-- Error message displayed when validation fails -->
    <div v-if="error" :class="styles.errorMessage">{{ error }}</div>

    <!-- Task description input field -->
    <div :class="styles.formGroup">
      <label for="taskText" :class="styles.label">Task Description:</label>
      <input
        type="text"
        id="taskText"
        v-model="text"
        placeholder="Enter task description"
        :class="styles.inputField"
        required
      />
    </div>

    <!-- Priority selection dropdown -->
    <div :class="styles.formGroup">
      <label for="taskPriority" :class="styles.label">Priority:</label>
      <select
        id="taskPriority"
        v-model="priority"
        :class="styles.selectField"
      >
        <option value="High">High</option>
        <option value="Medium">Medium</option>
        <option value="Low">Low</option>
      </select>
    </div>

    <!-- Due date input field -->
    <div :class="styles.formGroup">
      <label for="taskDueDate" :class="styles.label">Due Date:</label>
      <input
        type="date"
        id="taskDueDate"
        v-model="dueDate"
        :class="styles.dateField"
      />
    </div>

    <!-- Submit button to add the task -->
    <button type="submit" :class="styles.submitButton">
      Add Task
    </button>
  </form>
</template>
