// apps/vue-todo-apps/src/components/TaskList.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useTaskStore, Task } from '../stores/taskStore';
import styles from '../styles/TaskList.module.css';

// Get the task store
const taskStore = useTaskStore();

// Properties for managing task editing state
const editTaskId = ref<string | null>(null);
const editTaskText = ref('');

// Sets up task editing mode
const handleEditClick = (task: Task) => {
  editTaskId.value = task.id;
  editTaskText.value = task.text;
};

// Saves edited task if valid text is provided
const handleEditSave = (id: string) => {
  if (editTaskText.value.trim()) {
    taskStore.updateTask(id, { text: editTaskText.value.trim() });
    editTaskId.value = null;
  }
};

// Cancels task editing mode
const handleCancelEdit = () => {
  editTaskId.value = null;
  editTaskText.value = '';
};

// Generates CSS classes for tasks based on completion and priority
const getTaskClassName = (task: Task) => {
  let className = styles.taskItem;

  if (task.completed) {
    className += ' ' + styles.completed;
  }

  if (task.priority === 'High') {
    className += ' ' + styles['high-priority'];
  } else if (task.priority === 'Medium') {
    className += ' ' + styles['medium-priority'];
  } else if (task.priority === 'Low') {
    className += ' ' + styles['low-priority'];
  }

  return className;
};

// Formats the date and checks if task is overdue
const formatDate = (dateString: string) => {
  if (!dateString) {
    return { formattedDate: '', isOverdue: false };
  }

  const options: Intl.DateTimeFormatOptions = {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  };

  const date = new Date(dateString);
  date.setMinutes(date.getMinutes() + date.getTimezoneOffset());
  const formattedDate = date.toLocaleDateString(undefined, options);

  const currentDate = new Date();
  const isOverdue = date < currentDate;

  return { formattedDate, isOverdue };
};
</script>

<template>
  <!-- Task list container -->
  <ul :class="styles.taskList">
    <!-- Iterates through each task -->
    <li
      v-for="task in taskStore.filteredTasks"
      :key="task.id"
      :class="getTaskClassName(task)"
    >
      <!-- Task content wrapper with checkbox and text -->
      <div :class="styles.taskContent">
        <!-- Checkbox for marking task complete -->
        <input
          type="checkbox"
          :checked="task.completed"
          @change="taskStore.toggleTaskCompletion(task.id)"
          :class="styles.taskCheckbox"
        />

        <!-- Edit mode container with input field and action buttons -->
        <template v-if="editTaskId === task.id">
          <div :class="styles.editInputWrapper">
            <!-- Input field for editing task text -->
            <input
              type="text"
              v-model="editTaskText"
              @blur="handleEditSave(task.id)"
              @keyup.enter="handleEditSave(task.id)"
              @keyup.escape="handleCancelEdit()"
              :class="styles.taskInput"
              ref="editInput"
              autofocus
            />
            <!-- Save button for edit mode -->
            <button
              @click="handleEditSave(task.id)"
              :class="styles.saveButton"
            >
              Save
            </button>
            <!-- Cancel button for edit mode -->
            <button
              @click="handleCancelEdit()"
              :class="styles.cancelButton"
            >
              Cancel
            </button>
          </div>
        </template>

        <!-- Display mode showing task text -->
        <template v-else>
          <span
            @dblclick="handleEditClick(task)"
            title="Double-click to edit"
            :class="styles.taskText"
          >
            {{ task.text }}
          </span>
        </template>

        <!-- Due date display with overdue highlighting -->
        <span v-if="task.dueDate" :class="styles.dueDate">
          Due: <strong :style="{ color: formatDate(task.dueDate).isOverdue ? 'red' : 'inherit' }">
            {{ formatDate(task.dueDate).formattedDate }}
          </strong>
        </span>
      </div>

      <!-- Action buttons -->
      <div
        :class="styles.taskActions"
      >
        <!-- Edit task button -->
        <button
          @click="handleEditClick(task)"
          :class="styles.editButton"
        >
          Edit
        </button>
        <!-- Delete task button -->
        <button
          @click="taskStore.deleteTask(task.id)"
          :class="styles.deleteButton"
        >
          Delete
        </button>
      </div>
    </li>
  </ul>
</template>

// apps/angular-todo-apps/src/app/components/task-list/task-list.component.ts
import {Component, EventEmitter, Input, Output, ChangeDetectionStrategy} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {Task} from '../../models/task';

// Main task list component that displays and manages tasks
@Component({
  selector: 'app-task-list',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './task-list.component.html',
  styleUrl: './task-list.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush // Improves performance by reducing change detection
})
export class TaskListComponent {
  // Input and output properties for task management
  @Input() tasks: Task[] = [];
  @Output() deleteTask = new EventEmitter<string>();
  @Output() toggleTaskCompletion = new EventEmitter<string>();
  @Output() updateTask = new EventEmitter<{ id: string, updatedTask: Partial<Task> }>();

  // Properties for managing task editing state
  editTaskId: string | null = null;
  editTaskText: string = '';
  hoveredTaskId: string | null = null;

  // Sets up task editing mode
  handleEditClick(task: Task): void {
    this.editTaskId = task.id;
    this.editTaskText = task.text;
  }

  // Saves edited task if valid text is provided
  handleEditSave(id: string): void {
    if (this.editTaskText.trim()) {
      this.updateTask.emit({
        id: id,
        updatedTask: {text: this.editTaskText.trim()}
      });
      this.editTaskId = null;
    }
  }

  // Cancels task editing mode
  handleCancelEdit(): void {
    this.editTaskId = null;
    this.editTaskText = '';
  }

  // Generates CSS classes for tasks based on completion and priority
  getTaskClassName(task: Task): string {
    let className = 'taskItem';

    if (task.completed) {
      className += ' completed';
    }

    if (task.priority === 'High') {
      className += ' high-priority';
    } else if (task.priority === 'Medium') {
      className += ' medium-priority';
    } else if (task.priority === 'Low') {
      className += ' low-priority';
    }

    return className;
  }

  // Formats the date and checks if task is overdue
  formatDate(dateString: string): { formattedDate: string, isOverdue: boolean } {
    if (!dateString) {
      return {formattedDate: '', isOverdue: false};
    }

    const options: Intl.DateTimeFormatOptions = {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    };

    const date = new Date(dateString);
    date.setMinutes(date.getMinutes() + date.getTimezoneOffset());
    const formattedDate = date.toLocaleDateString(undefined, options);

    const currentDate = new Date();
    const isOverdue = date < currentDate;

    return {formattedDate, isOverdue};
  }
}

<!-- Task list container -->
<ul class="taskList">
  <!-- Iterates through each task and handles hover states -->
  <li
    *ngFor="let task of tasks"
    [class]="getTaskClassName(task)"
    (mouseenter)="hoveredTaskId = task.id"
    (mouseleave)="hoveredTaskId = null"
  >
    <!-- Task content wrapper with checkbox and text -->
    <div class="taskContent">
      <!-- Checkbox for marking task complete -->
      <input
        type="checkbox"
        [checked]="task.completed"
        (change)="toggleTaskCompletion.emit(task.id)"
        class="taskCheckbox"
      />

      <!-- Edit mode container with input field and action buttons -->
      <ng-container *ngIf="editTaskId === task.id; else displayMode">
        <div class="editInputWrapper">
          <!-- Input field for editing task text -->
          <input
            type="text"
            [(ngModel)]="editTaskText"
            (blur)="handleEditSave(task.id)"
            (keydown.enter)="handleEditSave(task.id)"
            (keydown.escape)="handleCancelEdit()"
            class="taskInput"
            #editInput
            autofocus
          />
          <!-- Save button for edit mode -->
          <button
            (click)="handleEditSave(task.id)"
            class="saveButton"
          >
            Save
          </button>
          <!-- Cancel button for edit mode -->
          <button
            (click)="handleCancelEdit()"
            class="cancelButton"
          >
            Cancel
          </button>
        </div>
      </ng-container>

      <!-- Display mode showing task text -->
      <ng-template #displayMode>
        <span
          (dblclick)="handleEditClick(task)"
          title="Double-click to edit"
          class="taskText"
        >
          {{ task.text }}
        </span>
      </ng-template>

      <!-- Due date display with overdue highlighting -->
      <span *ngIf="task.dueDate" class="dueDate">
        Due: <strong [style.color]="formatDate(task.dueDate).isOverdue ? 'red' : 'inherit'">
          {{ formatDate(task.dueDate).formattedDate }}
        </strong>
      </span>
    </div>

    <!-- Action buttons that appear on hover -->
    <div
      class="taskActions"
      [class.actionsVisible]="hoveredTaskId === task.id"
    >
      <!-- Edit task button -->
      <button
        (click)="handleEditClick(task)"
        class="editButton"
      >
        Edit
      </button>
      <!-- Delete task button -->
      <button
        (click)="deleteTask.emit(task.id)"
        class="deleteButton"
      >
        Delete
      </button>
    </div>
  </li>
</ul>
