// apps/vue-todo-apps/src/App.vue
<script setup lang="ts">
import { computed } from 'vue';
import TaskForm from './components/TaskForm.vue';
import TaskList from './components/TaskList.vue';
import Filters from './components/Filters.vue';
import styles from './styles/App.module.css';

// Helper method to display current year in footer
const getCurrentYear = computed(() => {
  return new Date().getFullYear();
});
</script>

<template>
  <div :class="styles.appContainer">
    <h1 :class="styles.appTitle">Senior Research To-Do List</h1>
    <h2 :class="styles.appTitle" style="color: green; text-decoration: underline">Vue.js Version</h2>
    <h3 :class="styles.appTitle">By Talal Shreidi</h3>

    <!-- Component for adding new tasks through a form interface -->
    <TaskForm />

    <!-- Component for filtering tasks -->
    <Filters />

    <!-- Component for displaying tasks -->
    <TaskList />

    <!-- Footer -->
    <footer style="text-align: center; padding: 1rem; background: #f1f1f1; margin-top: 1rem;">
      © {{ getCurrentYear }} <span style="font-weight: bold;">CSC 450 Senior Research</span>. All Rights Reserved.
    </footer>
  </div>
</template>

// apps/angular-todo-apps/src/app/app.component.ts
import {Component, OnInit} from '@angular/core';
import {RouterOutlet} from '@angular/router';
import {CommonModule} from '@angular/common';
import {TaskFormComponent} from './components/task-form/task-form.component';
import {TaskListComponent} from './components/task-list/task-list.component';
import {FiltersComponent} from './components/filters/filters.component';
import {TaskService} from './services/task.service';
import {Task} from './models/task';

// Main app component that orchestrates the todo list functionality
@Component({
    selector: 'app-root',
    standalone: true,
    imports: [
        RouterOutlet,
        CommonModule,
        TaskFormComponent,
        TaskListComponent,
        FiltersComponent
    ],
    templateUrl: './app.component.html',
    styleUrl: './app.component.css'
})
export class AppComponent implements OnInit {
    title = 'Senior Research To-Do List';
    tasks: Task[] = []; // Holds the list of tasks
    filter = 'all'; // Current filter state (all/active/completed)

    constructor(private taskService: TaskService) {
    }

    ngOnInit(): void {
        // Listen for changes in tasks and filter selection
        this.taskService.getTasks().subscribe(tasks => {
            this.tasks = tasks;
        });

        this.taskService.getFilter().subscribe(filter => {
            this.filter = filter;
        });
    }

    // Handles adding a new task
    onAddTask(task: Omit<Task, 'id'>): void {
        this.taskService.addTask(task);
    }

    // Updates existing task details
    onUpdateTask(id: string, updatedTask: Partial<Task>): void {
        this.taskService.updateTask(id, updatedTask);
    }

    // Removes a task from the list
    onDeleteTask(id: string): void {
        this.taskService.deleteTask(id);
    }

    // Toggles the completion status of a task
    onToggleTaskCompletion(id: string): void {
        this.taskService.toggleTaskCompletion(id);
    }

    // Updates the current filter selection
    onFilterChange(filter: string): void {
        this.taskService.setFilter(filter);
    }

    // Gets filtered tasks based on current filter
    getFilteredTasks(): Task[] {
        return this.taskService.getFilteredTasks();
    }

    // Helper method to display current year in footer
    getCurrentYear(): number {
        return new Date().getFullYear();
    }
}

<div class="appContainer">
  <h1 class="appTitle">Senior Research To-Do List</h1>
    <h2 class="appTitle" id="version-app">Angular Version</h2>
  <h3 class="appTitle">By Talal Shreidi</h3>

  <!-- Component for adding new tasks through a form interface -->

  <app-task-form (addTask)="onAddTask($event)"></app-task-form>

  <app-filters [filter]="filter" (filterChange)="onFilterChange($event)"></app-filters>

 <!-- Component for displaying tasks -->

  <app-task-list
    [tasks]="getFilteredTasks()"
    (deleteTask)="onDeleteTask($event)"
    (toggleTaskCompletion)="onToggleTaskCompletion($event)"
    (updateTask)="onUpdateTask($event.id, $event.updatedTask)"
  ></app-task-list>

 <!-- Footer -->
  <footer style="text-align: center; padding: 1rem; background: #f1f1f1; margin-top: 1rem;">
    © {{ getCurrentYear() }} <span style="font-weight: bold;">CSC 450 Senior Research</span>. All Rights Reserved.
  </footer>
</div>

<router-outlet />
